import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import RedirectButton from "@/components/redirectButton";
import FooterLink from "@/components/footerLink";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  
  return (
    <html lang="fr" data-theme="emerald">
      <body>
        <div className="navbar bg-neutral text-neutral-content shadow-sm">
          <div className="navbar-start">
            <div className="dropdown">
              <div tabIndex={0} role="button" className="btn btn-ghost btn-circle">
                <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h7" /> </svg>
              </div>
              <ul
                tabIndex={0}
                className="menu menu-sm dropdown-content bg-neutral rounded-box z-1 mt-3 w-52 p-2 shadow">
                <li><RedirectButton link="/" text="Accueil" theme="primary"/></li>
                <li><RedirectButton link="/about" text="À propos" theme="primary"/></li>
                <li><RedirectButton link="/portfolio" text="Portfolio" theme="primary"/></li>
              </ul>
            </div>
          </div>
          <div className="navbar-center">
            <a className="btn btn-ghost text-xl">benone.ch</a>
          </div>
          <div className="navbar-end">
            <RedirectButton link="/login" text="connexion" theme="primary"/>
          </div>
        </div>
        <main>
          {children}
        </main>
        <footer className="footer sm:footer-horizontal bg-neutral text-neutral-content p-10">
          <nav>
            <h6 className="footer-title">benone.ch</h6>
            <FooterLink link="/about" text="À propos" />
            <FooterLink link="/portfolio" text="Portfolio" />
            <FooterLink link="/contact-us" text="Me contacter" />
          </nav>
          <nav>
            <h6 className="footer-title">Legal</h6>
            <FooterLink link="/legal-mentions" text="Mentions légales" />
            <FooterLink link="/confidentiality" text="Confidentialités" />
          </nav>
        </footer>
      </body>
    </html>
  );
}
